# 파일 이름: .github/workflows/test-push-permission.yml

name: Test Push Permission

# 이 워크플로우는 수동으로만 실행됩니다.
on:
  workflow_dispatch:

jobs:
  test-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 쓰기 권한 부여

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # PAT를 사용하는 것이 핵심입니다.
          token: ${{ secrets.MY_PAT }}

      - name: Create a test file
        run: |
          # 테스트 파일 생성 및 현재 시간 기록
          echo "테스트 시간: $(date)" > test-file.txt

      - name: Commit and push test file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "test: 워크플로우 푸시 권한 테스트"
          file_pattern: test-file.txt
          commit_user_name: GitHub Actions [bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com